# Generated by Django 5.1.3 on 2024-11-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_is_urgent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='time_to_read',
        ),
        migrations.AddField(
            model_name='post',
            name='podcast',
            field=models.FileField(blank=True, null=True, upload_to='podcasts', verbose_name='پادکست'),
        ),
    ]
