# Generated by Django 5.1.3 on 2024-11-20 07:50

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_is_published_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='author',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تلگرام'),
        ),
        migrations.AlterField(
            model_name='post',
            name='podcast',
            field=models.FileField(blank=True, null=True, upload_to='podcasts', validators=[blog.models.validate_mp3_file], verbose_name='پادکست'),
        ),
    ]
