# Generated by Django 5.1.3 on 2024-11-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_channel', models.CharField(max_length=255, verbose_name='کانال تلگرام')),
                ('telegram_member', models.IntegerField(verbose_name='تعداد اعضای کانال')),
                ('instagram_page', models.CharField(max_length=255, verbose_name='صفحه اینستاگرام')),
                ('instagram_follower', models.IntegerField(verbose_name='تعداد فالوور های صفحه')),
            ],
        ),
    ]
