# Generated by Django 5.1.3 on 2024-11-18 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'رسانه های اجتماعی', 'verbose_name_plural': 'رسانه های اجتماعی'},
        ),
    ]
